// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Vault.UI.AdminForm.ClientApi
{
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for VaultAPI.
    /// </summary>
    public static partial class VaultAPIExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<Book>> BookGetAllAsync(this IVaultAPI operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.BookGetAllWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='author'>
            /// </param>
            /// <param name='name'>
            /// </param>
            /// <param name='isAvailable'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<Book> BookCreateAsync(this IVaultAPI operations, int? id = default(int?), string author = default(string), string name = default(string), bool? isAvailable = default(bool?), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.BookCreateWithHttpMessagesAsync(id, author, name, isAvailable, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<Book> BookGetAsync(this IVaultAPI operations, int id, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.BookGetWithHttpMessagesAsync(id, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='id1'>
            /// </param>
            /// <param name='author'>
            /// </param>
            /// <param name='name'>
            /// </param>
            /// <param name='isAvailable'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<Book> BookUpdateAsync(this IVaultAPI operations, int id, int id1, string author = default(string), string name = default(string), bool? isAvailable = default(bool?), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.BookUpdateWithHttpMessagesAsync(id, id1, author, name, isAvailable, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<Lender>> LenderGetAllAsync(this IVaultAPI operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.LenderGetAllWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='name'>
            /// </param>
            /// <param name='email'>
            /// </param>
            /// <param name='lendingHistory'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<Lender> LenderCreateAsync(this IVaultAPI operations, int? id = default(int?), string name = default(string), string email = default(string), IList<object> lendingHistory = default(IList<object>), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.LenderCreateWithHttpMessagesAsync(id, name, email, lendingHistory, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<Lender> LenderGetAsync(this IVaultAPI operations, int id, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.LenderGetWithHttpMessagesAsync(id, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='id1'>
            /// </param>
            /// <param name='name'>
            /// </param>
            /// <param name='email'>
            /// </param>
            /// <param name='lendingHistory'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<Lender> LenderUpdateAsync(this IVaultAPI operations, int id, int id1, string name = default(string), string email = default(string), IList<object> lendingHistory = default(IList<object>), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.LenderUpdateWithHttpMessagesAsync(id, id1, name, email, lendingHistory, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='bookId'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<LendingRecord> LendingFindAsync(this IVaultAPI operations, int bookId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.LendingFindWithHttpMessagesAsync(bookId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<LendingRecord>> LendingGetAllAsync(this IVaultAPI operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.LendingGetAllWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='lenderId'>
            /// </param>
            /// <param name='lenderName'>
            /// </param>
            /// <param name='lenderEmail'>
            /// </param>
            /// <param name='lenderLendingHistory'>
            /// </param>
            /// <param name='bookId'>
            /// </param>
            /// <param name='bookAuthor'>
            /// </param>
            /// <param name='bookName'>
            /// </param>
            /// <param name='bookIsAvailable'>
            /// </param>
            /// <param name='fromParameter'>
            /// </param>
            /// <param name='to'>
            /// </param>
            /// <param name='returned'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<LendingRecord> LendingCreateAsync(this IVaultAPI operations, int? id = default(int?), int? lenderId = default(int?), string lenderName = default(string), string lenderEmail = default(string), IList<object> lenderLendingHistory = default(IList<object>), int? bookId = default(int?), string bookAuthor = default(string), string bookName = default(string), bool? bookIsAvailable = default(bool?), System.DateTime? fromParameter = default(System.DateTime?), System.DateTime? to = default(System.DateTime?), System.DateTime? returned = default(System.DateTime?), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.LendingCreateWithHttpMessagesAsync(id, lenderId, lenderName, lenderEmail, lenderLendingHistory, bookId, bookAuthor, bookName, bookIsAvailable, fromParameter, to, returned, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<LendingRecord> LendingGetAsync(this IVaultAPI operations, int id, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.LendingGetWithHttpMessagesAsync(id, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='id1'>
            /// </param>
            /// <param name='lenderId'>
            /// </param>
            /// <param name='lenderName'>
            /// </param>
            /// <param name='lenderEmail'>
            /// </param>
            /// <param name='lenderLendingHistory'>
            /// </param>
            /// <param name='bookId'>
            /// </param>
            /// <param name='bookAuthor'>
            /// </param>
            /// <param name='bookName'>
            /// </param>
            /// <param name='bookIsAvailable'>
            /// </param>
            /// <param name='fromParameter'>
            /// </param>
            /// <param name='to'>
            /// </param>
            /// <param name='returned'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<LendingRecord> LendingUpdateAsync(this IVaultAPI operations, int id, int id1, int? lenderId = default(int?), string lenderName = default(string), string lenderEmail = default(string), IList<object> lenderLendingHistory = default(IList<object>), int? bookId = default(int?), string bookAuthor = default(string), string bookName = default(string), bool? bookIsAvailable = default(bool?), System.DateTime? fromParameter = default(System.DateTime?), System.DateTime? to = default(System.DateTime?), System.DateTime? returned = default(System.DateTime?), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.LendingUpdateWithHttpMessagesAsync(id, id1, lenderId, lenderName, lenderEmail, lenderLendingHistory, bookId, bookAuthor, bookName, bookIsAvailable, fromParameter, to, returned, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
