// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Vault.UI.AdminForm.ClientApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Book
    {
        /// <summary>
        /// Initializes a new instance of the Book class.
        /// </summary>
        public Book()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Book class.
        /// </summary>
        public Book(int? id = default(int?), string author = default(string), string name = default(string), Location location = default(Location), bool? isAvailable = default(bool?), IList<Picture> pictures = default(IList<Picture>))
        {
            Id = id;
            Author = author;
            Name = name;
            Location = location;
            IsAvailable = isAvailable;
            Pictures = pictures;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "author")]
        public string Author { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "location")]
        public Location Location { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isAvailable")]
        public bool? IsAvailable { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pictures")]
        public IList<Picture> Pictures { get; set; }

    }
}
