// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Vault.UI.AdminForm.ClientApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class LendingRecord
    {
        /// <summary>
        /// Initializes a new instance of the LendingRecord class.
        /// </summary>
        public LendingRecord()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the LendingRecord class.
        /// </summary>
        public LendingRecord(int? id = default(int?), Lender lender = default(Lender), Book book = default(Book), System.DateTime? fromProperty = default(System.DateTime?), System.DateTime? to = default(System.DateTime?), System.DateTime? returned = default(System.DateTime?))
        {
            Id = id;
            Lender = lender;
            Book = book;
            FromProperty = fromProperty;
            To = to;
            Returned = returned;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lender")]
        public Lender Lender { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "book")]
        public Book Book { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "from")]
        public System.DateTime? FromProperty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "to")]
        public System.DateTime? To { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "returned")]
        public System.DateTime? Returned { get; set; }

    }
}
