// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Vault.UI.AdminForm.ClientApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Lender
    {
        /// <summary>
        /// Initializes a new instance of the Lender class.
        /// </summary>
        public Lender()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Lender class.
        /// </summary>
        public Lender(int? id = default(int?), string name = default(string), string email = default(string), IList<LendingRecord> lendingHistory = default(IList<LendingRecord>))
        {
            Id = id;
            Name = name;
            Email = email;
            LendingHistory = lendingHistory;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lendingHistory")]
        public IList<LendingRecord> LendingHistory { get; set; }

    }
}
