// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Vault.UI.AdminForm.ClientApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Picture
    {
        /// <summary>
        /// Initializes a new instance of the Picture class.
        /// </summary>
        public Picture()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Picture class.
        /// </summary>
        public Picture(int? id = default(int?), Book book = default(Book), byte[] bytes = default(byte[]))
        {
            Id = id;
            Book = book;
            Bytes = bytes;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "book")]
        public Book Book { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bytes")]
        public byte[] Bytes { get; set; }

    }
}
